### ISSUE TITLE
Upgrade Empty Cabins 1.1.0 - Dialogue Errors

### ISSUE THREAD

**Issue by XTFOX** [ChroniclerCherry/stardew-valley-mods#93]
When attempting to upgrade a cabin I get using the alpha build I get the following error:

[game] An error occurred in the base update loop: Microsoft.Xna.Framework.Content.ContentLoadException: Unable to parse string path: Thank you! I'll get started tomorrow. I should be finished in around three days.
   at StardewValley.LocalizedContentManager.parseStringPath(String path, String& assetName, String& key) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalizedContentManager.cs:line 760
   at StardewValley.LocalizedContentManager.LoadString(String path) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalizedContentManager.cs:line 640
   at StardewValley.NPC.setNewDialogue(String translationKey, Boolean add, Boolean clearOnMovement) in **D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\NPC.cs:line 5188
   at UpgradeEmptyCabins.UpgradeCabins.HouseUpgradeAccept(Building cab) in C:\Users\jeffc\Documents\Stardew Valley\Modding\UpgradeEmptyCabins\ModEntry.cs:line 271**
   at UpgradeEmptyCabins.UpgradeCabins.<AskForUpgrade>b__12_0(Farmer who, String answer) in C:\Users\jeffc\Documents\Stardew Valley\Modding\UpgradeEmptyCabins\ModEntry.cs:line 252
   at StardewValley.GameLocation.answerDialogue(Response answer) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Locations\GameLocation.cs:line 13125
   at StardewValley.Menus.DialogueBox.receiveLeftClick(Int32 x, Int32 y, Boolean playSound) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Menus\DialogueBox.cs:line 376
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 4797
   at StardewValley.Game1._update(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 4024
   at StardewValley.Game1.Update(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 3199
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 1083
[game] WARNING: Mismatched UI Mode Push/Pop counts. Correcting.

Potential Solution:
Here is the code in the mod from line 271:
Game1.getCharacterFromName("Robin").setNewDialogue(Game1.content.LoadString("Data\\ExtraDialogue:Robin_HouseUpgrade_Accepted"));
Game1.drawDialogue(Game1.getCharacterFromName("Robin"));

It seems like "Game1.content.LoadString" may no longer be necessary and that setNewDialogue is trying to read from the localization string path. I did some testing and confirmed that if I removed "Game1.content.LoadString" from this line the dialogue box now appears correctly in game when attempting to build an upgrade.

Note that my testing was done with InstantBuild enabled but in general gameplay I saw that the confirmation dialogue was not appearing as well. This likely means that "Game1.content.LoadString" would also need to be removed from any lines that use setNewDialogue:
271
287
304
320

**Comment by Pathoschild** [comment]
Fixed via #94 in Empty Cabins 1.2.0. Thanks for reporting it!
